theme: jekyll-theme-tactile

title: What do we have here? A peak into Maia's public projects
description: Stay tuned as more become available!

More: My goal over the next few months is to share my the code I've written in the past, create new projects, and learn from the community. I have a personal webiste that you can see [here](MaiaKaplan.com), which is also under being populated.

My goal is to share something every week, and I would love feedback on any of it. Feel free to send me an email directly at Kaplan(dot)Maia(at)gmail(dot)com or stay tuned while I sort out how to make a contact form!  (I'm so excited, it's funny!)


